import { describe, expect, it } from "vitest";
import vectors from "./fixtures/work-command-v2.json";
import {
  commandNodeFrameSchema,
  commandProtocolVersion,
  commandServerFrameSchema,
  parseCommandFrame,
} from "./work-command.js";

/** Generated by the actual frozen Python frame parser; the generator and source hashes ship with the packet. */
describe("candidate command v2 Python parity", () => {
  it.each(vectors)("$name", async (row) => {
    if (row.accepted) {
      await expect(parseCommandFrame(row.value, { server: row.server })).resolves.toEqual(
        row.parsed,
      );
    } else {
      await expect(parseCommandFrame(row.value, { server: row.server })).rejects.toThrow(
        "invalid_command_frame",
      );
    }
  });

  it("defines a candidate command version without updating the shared Node handshake", () => {
    expect(commandProtocolVersion).toBe("0.10.0");
  });

  it("safeParseAsync reports malformed output base64 without throwing", async () => {
    const row = vectors.find((value) => value.name === "node:work.command.output_chunk");
    const value = structuredClone(row?.value) as Record<string, unknown>;
    value.payload = { fileIndex: 0, offset: 0, data: "abc==" };
    expect((await commandNodeFrameSchema.safeParseAsync(value)).success).toBe(false);
  });

  it("rejects unsupported local JS values without invoking accessors or serialization hooks", async () => {
    let calls = 0;
    const row = vectors.find((value) => value.name === "server:work.command.prepare_open");
    const value = structuredClone(row?.value) as Record<string, unknown>;
    const getter = { ...value };
    Object.defineProperty(getter, "extra", {
      enumerable: true,
      get() {
        calls += 1;
        return 1;
      },
    });
    const cyclic = { ...value };
    cyclic.extra = cyclic;
    const symbolic = { ...value, [Symbol("synthetic")]: 1 };
    for (const candidate of [
      undefined,
      NaN,
      Infinity,
      1n,
      Symbol(),
      new Date(),
      Object.create({ type: "work.command.prepare_open" }),
      getter,
      cyclic,
      symbolic,
      {
        ...value,
        toJSON() {
          calls += 1;
          return value;
        },
      },
    ]) {
      await expect(parseCommandFrame(candidate, { server: true })).rejects.toThrow(
        "invalid_command_frame",
      );
    }
    expect(calls).toBe(0);
    expect((await commandServerFrameSchema.safeParseAsync(getter)).success).toBe(false);
  });
});
